// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw4ynlwDBo-kMwASzJfJV6jaD4vjiphu4',
    appId: '1:1084056746305:web:f296b7b3a7af909be9c9c0',
    messagingSenderId: '1084056746305',
    projectId: 'parked-3ea74',
    authDomain: 'parked-3ea74.firebaseapp.com',
    databaseURL: 'https://parked-3ea74-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'parked-3ea74.appspot.com',
    measurementId: 'G-SZVSSKJY5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApJyFiW3YhI9D49EbDCSwgt3XgZ9VotRM',
    appId: '1:1084056746305:android:797b473c93d0187ce9c9c0',
    messagingSenderId: '1084056746305',
    projectId: 'parked-3ea74',
    databaseURL: 'https://parked-3ea74-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'parked-3ea74.appspot.com',
  );
}
